server:
  port: 8088
spring:
  main:
    #allow-circular-references ?true?????????
    allow-circular-references: true
  # #???
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      ##?????????filters????????sgl?????'wall'??????slf4i(?log4j?????????????)
      filters: stat
      url: jdbc:mysql:///mysql?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Sas61223
      initial-size: 1
      min-idle: 1 #???????
      max-active: 20 #??????
      max-wait: 60000 #???????????????
      ##??????????minEvictableIdleTimeMillis???????????????min-idle???1????-?
      time-between-evict-runs-millis: 60000
      #??????????
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      #?????????????????
      test-while-idle: true
      #????????????
      test-on-borrow: false
      # #????????????
      test-on-return: false
      #????prepareStatement
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20



